import type { Metadata } from "next";
import "./globals.css";

import localFont from 'next/font/local'
import TitleBand from "./components/TitleBand";
const EduDiatype = localFont({ 
  src: './EduDiatype-Regular.woff2',
  display: 'swap',
  variable: '--diatype',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={EduDiatype.className}>
        {children}
        </body>
    </html>
  );
}
